
name: Debug Garnix Event
on:
  check_run:
    types: [completed]

jobs:
  inspect-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Entire Event Context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"
